export const seedAuthor = {
  userId: null,
  name: 'Gluten Free Map',
  email: 'seed@glutenfreemap.local',
  role: 'admin',
}

export const seedListings = [
  {
    id: 'seed-physical-1',
    kind: 'physical',
    name: 'Pan Libre Palermo',
    category: 'restaurant',
    city: 'Palermo, CABA',
    address: 'Honduras 4780',
    coordinates: [-34.58831, -58.42864],
    websiteUrl: null,
    description:
      'Bistro con cocina 100% sin TACC, brunch y menu corto pensado para celiacos.',
    tags: ['100% sin TACC', 'brunch', 'opciones veganas', 'cocina dedicada'],
    products: ['empanadas', 'pastas frescas', 'tortas'],
    verified: true,
    dedicatedKitchen: true,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-20T18:30:00.000Z',
    createdAt: '2026-03-20T18:30:00.000Z',
    updatedAt: '2026-03-20T18:30:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'seed-physical-2',
    kind: 'physical',
    name: 'Despensa Celia Norte',
    category: 'store',
    city: 'Belgrano, CABA',
    address: 'Juramento 2448',
    coordinates: [-34.56284, -58.45734],
    websiteUrl: null,
    description:
      'Local especializado en premezclas, snacks y congelados con referencias claras por marca.',
    tags: ['congelados', 'economico'],
    products: ['premezcla', 'ravioles congelados', 'galletitas'],
    verified: true,
    dedicatedKitchen: false,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-18T14:10:00.000Z',
    createdAt: '2026-03-18T14:10:00.000Z',
    updatedAt: '2026-03-18T14:10:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'seed-physical-3',
    kind: 'physical',
    name: 'Mercado Apto Caballito',
    category: 'market',
    city: 'Caballito, CABA',
    address: 'Av. Rivadavia 5602',
    coordinates: [-34.61817, -58.43846],
    websiteUrl: null,
    description:
      'Sucursal con gondola dedicada, heladeras separadas y stock estable de productos certificados.',
    tags: ['supermercado', 'delivery', 'freezer'],
    products: ['cerveza sin gluten', 'pan lactal', 'postres'],
    verified: false,
    dedicatedKitchen: false,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-16T11:45:00.000Z',
    createdAt: '2026-03-16T11:45:00.000Z',
    updatedAt: '2026-03-16T11:45:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'seed-physical-4',
    kind: 'physical',
    name: 'Cafe Cero Migas',
    category: 'restaurant',
    city: 'Villa Crespo, CABA',
    address: 'Thames 612',
    coordinates: [-34.59862, -58.43975],
    websiteUrl: null,
    description:
      'Cafeteria con protocolo de contaminacion cruzada, pasteleria chica y menu de mediodia.',
    tags: ['pasteleria', 'take away', 'desayuno', 'cocina dedicada'],
    products: ['medialunas', 'cookies', 'sandwiches'],
    verified: false,
    dedicatedKitchen: true,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-14T16:20:00.000Z',
    createdAt: '2026-03-14T16:20:00.000Z',
    updatedAt: '2026-03-14T16:20:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'seed-online-1',
    kind: 'online',
    name: 'Tienda Sin Harina',
    category: 'onlineStore',
    city: null,
    address: null,
    coordinates: null,
    websiteUrl: 'https://example.com/tienda-sin-harina',
    description:
      'Tienda online con envios a todo el pais y foco en panificados, freezer y desayunos aptos.',
    tags: ['envios', 'ecommerce', 'freezer'],
    products: ['pan lactal', 'prepizzas', 'medialunas'],
    verified: true,
    dedicatedKitchen: false,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-19T09:05:00.000Z',
    createdAt: '2026-03-19T09:05:00.000Z',
    updatedAt: '2026-03-19T09:05:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'seed-online-2',
    kind: 'online',
    name: 'Catalogo Celiaco Express',
    category: 'onlineStore',
    city: null,
    address: null,
    coordinates: null,
    websiteUrl: 'https://example.com/catalogo-celiaco-express',
    description:
      'Marketplace curado por la comunidad para encontrar snacks, mixes y marcas nuevas sin depender de una direccion fisica.',
    tags: ['marketplace', 'marcas nuevas', 'envios'],
    products: ['snacks', 'mix para tortas', 'alfajores'],
    verified: false,
    dedicatedKitchen: false,
    source: 'seed',
    approvalStatus: 'approved',
    submittedBy: seedAuthor,
    approvedByName: seedAuthor.name,
    approvedAt: '2026-03-17T13:00:00.000Z',
    createdAt: '2026-03-17T13:00:00.000Z',
    updatedAt: '2026-03-17T13:00:00.000Z',
    photos: [],
    reviews: [],
  },
]
