export const demoAuthor = {
  userId: 'demo-admin',
  name: 'Admin Gluten Free Map',
  email: 'admin@celiac-map.local',
  role: 'admin',
  authMethod: 'demo-admin',
}

export const seedPlaces = [
  {
    id: 'demo-1',
    name: 'Pan Libre Palermo',
    category: 'restaurant',
    city: 'Palermo, CABA',
    address: 'Honduras 4780',
    coordinates: [-34.58831, -58.42864],
    description:
      'Bistro demo con cocina 100% sin TACC, brunch y carta corta pensada para celiacos.',
    tags: ['100% sin TACC', 'brunch', 'opciones veganas', 'cocina dedicada'],
    products: ['empanadas', 'pastas frescas', 'tortas'],
    verified: true,
    dedicatedKitchen: true,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-20T18:30:00.000Z',
    updatedAt: '2026-03-20T18:30:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'demo-2',
    name: 'Despensa Celia Norte',
    category: 'store',
    city: 'Belgrano, CABA',
    address: 'Juramento 2448',
    coordinates: [-34.56284, -58.45734],
    description:
      'Local demo enfocado en harinas, premezclas y snacks con referencias visibles por marca.',
    tags: ['congelados', 'economico'],
    products: ['premezcla', 'ravioles congelados', 'galletitas'],
    verified: true,
    dedicatedKitchen: false,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-18T14:10:00.000Z',
    updatedAt: '2026-03-18T14:10:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'demo-3',
    name: 'Mercado Apto Caballito',
    category: 'market',
    city: 'Caballito, CABA',
    address: 'Av. Rivadavia 5602',
    coordinates: [-34.61817, -58.43846],
    description:
      'Sucursal demo con gondola dedicada, heladeras separadas y stock estable de productos certificados.',
    tags: ['supermercado', 'delivery', 'freezer'],
    products: ['cerveza sin gluten', 'pan lactal', 'postres'],
    verified: false,
    dedicatedKitchen: false,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-16T11:45:00.000Z',
    updatedAt: '2026-03-16T11:45:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'demo-4',
    name: 'Cafe Cero Migas',
    category: 'restaurant',
    city: 'Villa Crespo, CABA',
    address: 'Thames 612',
    coordinates: [-34.59862, -58.43975],
    description:
      'Cafeteria demo con protocolo de contaminacion cruzada, pasteleria chica y menu de mediodia.',
    tags: ['pasteleria', 'take away', 'desayuno', 'cocina dedicada'],
    products: ['medialunas', 'cookies', 'sandwiches'],
    verified: false,
    dedicatedKitchen: true,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-14T16:20:00.000Z',
    updatedAt: '2026-03-14T16:20:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'demo-5',
    name: 'Punto Sin Trigo Saavedra',
    category: 'productSpot',
    city: 'Saavedra, CABA',
    address: 'Av. Balbin 4120',
    coordinates: [-34.55429, -58.48731],
    description:
      'Negocio demo relevado por la comunidad por vender muchas marcas aptas aunque no sea exclusivo.',
    tags: ['freezer', 'delivery'],
    products: ['milanesas rebozadas', 'tapas de empanadas', 'alfajores'],
    verified: true,
    dedicatedKitchen: false,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-19T09:05:00.000Z',
    updatedAt: '2026-03-19T09:05:00.000Z',
    photos: [],
    reviews: [],
  },
  {
    id: 'demo-6',
    name: 'Esquina Verde Almagro',
    category: 'store',
    city: 'Almagro, CABA',
    address: 'Sarmiento 4012',
    coordinates: [-34.60966, -58.42419],
    description:
      'Dietetica demo con combos semanales, etiquetas claras y recomendacion de productos economicos.',
    tags: ['economico', 'delivery'],
    products: ['pre pizzas', 'granolas', 'mix para pancakes'],
    verified: false,
    dedicatedKitchen: false,
    source: 'demo',
    approvalStatus: 'approved',
    submittedBy: demoAuthor,
    approvedByName: demoAuthor.name,
    approvedAt: '2026-03-17T13:00:00.000Z',
    updatedAt: '2026-03-17T13:00:00.000Z',
    photos: [],
    reviews: [],
  },
]
